# Site settings
title: stwcx.
tagline: Do you have a reservation?
email: patrick@stwcx.xyz
description: > # this means to ignore newlines until "baseurl:"
    stwcx. is a Power assembly instruction: Store Word Conditional
    Indexed.  Paired with lwarx, and appropriate memory barriers, it
    performs an atomic operation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stwcx.xyz" # the base hostname & protocol for your site
twitter_username: williamspatrick
github_username:  williamspatrick

# Build settings
markdown: kramdown
